### ISSUE TITLE
Required string

### ISSUE THREAD

**Issue by dragosperca** [serbanrobu/purestruct#1]
given a string that is required, the library checks it with 

`public function required(): static
    {
        return static::mixed()
            ->bind(fn (mixed $v) => empty($v) ? static::fail('This field is required') : $this);
    }`

https://github.com/serbanrobu/purestruct/blob/main/src/Validator.php#L77

The check fails when the value provided is "0" (zero) since empty("0") == true
A better check would be using strlen($v) > 0?

**Comment by serbanrobu** [comment]
Nice catch! I didn't know about this behavior. I would like to support all types though, not just string. But sure I have to put different condition depending on the type.

**Comment by dragosperca** [comment]
thank you Serban, much appreciated!
